# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - conda-forge

dependencies:
  - python==3.8.12
  - pip
  - pip:
    - matplotlib
    - numpy
    - scipy
    - shapely
